@startuml
set namespaceSeparator ::

class "david_perez::auth::auth_page.dart::AuthPage" {
  +State<AuthPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::auth::auth_page.dart::AuthPage"

class "david_perez::auth::auth_page.dart::_AuthPageState" {
  +bool showLoginPage
  +void toggleScreens()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "david_perez::auth::auth_page.dart::_AuthPageState"

class "david_perez::auth::google_auth.dart::GoogleAuth" {
  -GoogleSignIn _googleSignIn
  -FirebaseAuth _auth
  +dynamic signOut()
  +dynamic signInWithGoogle()
  -dynamic _showPasswordDialog()
}

"david_perez::auth::google_auth.dart::GoogleAuth" o-- "google_sign_in::google_sign_in.dart::GoogleSignIn"
"david_perez::auth::google_auth.dart::GoogleAuth" o-- "firebase_auth::firebase_auth.dart::FirebaseAuth"

class "david_perez::auth::main_page.dart::MainPage" {
  +State<MainPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::auth::main_page.dart::MainPage"

class "david_perez::auth::main_page.dart::_MainPageState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "david_perez::auth::main_page.dart::_MainPageState"

class "david_perez::firebase_options.dart::DefaultFirebaseOptions" {
  {static} +FirebaseOptions web
  {static} +FirebaseOptions android
  {static} +FirebaseOptions ios
  {static} +FirebaseOptions macos
  {static} +FirebaseOptions currentPlatform
}

"david_perez::firebase_options.dart::DefaultFirebaseOptions" o-- "firebase_core_platform_interface::firebase_core_platform_interface.dart::FirebaseOptions"

class "david_perez::main.dart::MyApp" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "david_perez::main.dart::MyApp"

class "david_perez::main.dart::AuthenticationService" {
  -FirebaseAuth _firebaseAuth
  +Stream<User?> authStateChanges
  +dynamic signOut()
}

"david_perez::main.dart::AuthenticationService" o-- "firebase_auth::firebase_auth.dart::FirebaseAuth"
"david_perez::main.dart::AuthenticationService" o-- "dart::async::Stream<User>"

class "david_perez::pages::bookings_page.dart::ListBookings" {
  +dynamic getProductById()
  -void _showFlipCardDialog()
  +dynamic getProductData()
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "david_perez::pages::bookings_page.dart::ListBookings"

class "david_perez::pages::calendars::calendar_ask_quote.dart::CalendarAskQuotes" {
  +User? user
  +State<CalendarAskQuotes> createState()
}

"david_perez::pages::calendars::calendar_ask_quote.dart::CalendarAskQuotes" o-- "firebase_auth::firebase_auth.dart::User"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::pages::calendars::calendar_ask_quote.dart::CalendarAskQuotes"

class "david_perez::pages::calendars::calendar_ask_quote.dart::_CalendarAskQuotesState" {
  -CalendarFormat _calendarFormat
  -DateTime _focusedDay
  -DateTime? _selectedDay
  +CalendarService calendarioService
  +void initState()
  -bool _isDaySelectable()
  -dynamic _allCitasOcupadas()
  -dynamic _agregarCita()
  -dynamic _getCitasOcupadas()
  -void _showCitasList()
  -List<String> _getCitas()
  +Widget build()
}

"david_perez::pages::calendars::calendar_ask_quote.dart::_CalendarAskQuotesState" o-- "table_calendar::src::shared::utils.dart::CalendarFormat"
"david_perez::pages::calendars::calendar_ask_quote.dart::_CalendarAskQuotesState" o-- "david_perez::pages::calendars::services::calendar_service.dart::CalendarService"
"flutter::src::widgets::framework.dart::State" <|-- "david_perez::pages::calendars::calendar_ask_quote.dart::_CalendarAskQuotesState"

class "david_perez::pages::calendars::calendar_quotes_page.dart::CalendarQuotesPage" {
  +User? user
  +State<CalendarQuotesPage> createState()
}

"david_perez::pages::calendars::calendar_quotes_page.dart::CalendarQuotesPage" o-- "firebase_auth::firebase_auth.dart::User"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::pages::calendars::calendar_quotes_page.dart::CalendarQuotesPage"

class "david_perez::pages::calendars::calendar_quotes_page.dart::_CalendarQuotesPageState" {
  -CalendarFormat _calendarFormat
  -DateTime _focusedDay
  -DateTime? _selectedDay
  +CalendarService calendarioService
  +void initState()
  -bool _isDaySelectable()
  -dynamic _allCitasOcupadas()
  -dynamic _agregarCita()
  -dynamic _getCitasOcupadas()
  -void _showCitasList()
  -List<String> _getCitas()
  +Widget build()
}

"david_perez::pages::calendars::calendar_quotes_page.dart::_CalendarQuotesPageState" o-- "table_calendar::src::shared::utils.dart::CalendarFormat"
"david_perez::pages::calendars::calendar_quotes_page.dart::_CalendarQuotesPageState" o-- "david_perez::pages::calendars::services::calendar_service.dart::CalendarService"
"flutter::src::widgets::framework.dart::State" <|-- "david_perez::pages::calendars::calendar_quotes_page.dart::_CalendarQuotesPageState"

class "david_perez::pages::calendars::calendar_worker_page.dart::CalendarWorker" {
  +String workerUid
  +User? user
  +_CalendarWorkerState createState()
}

"david_perez::pages::calendars::calendar_worker_page.dart::CalendarWorker" o-- "firebase_auth::firebase_auth.dart::User"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::pages::calendars::calendar_worker_page.dart::CalendarWorker"

class "david_perez::pages::calendars::calendar_worker_page.dart::_CalendarWorkerState" {
  +CalendarFormat calendarFormat
  -DateTime _focusedDay
  -DateTime? _selectedDay
  +String workerEmail
  +dynamic getEventsOfDay()
  +void initState()
  +dynamic dayHasTasks()
  +Widget build()
}

"david_perez::pages::calendars::calendar_worker_page.dart::_CalendarWorkerState" o-- "table_calendar::src::shared::utils.dart::CalendarFormat"
"flutter::src::widgets::framework.dart::State" <|-- "david_perez::pages::calendars::calendar_worker_page.dart::_CalendarWorkerState"

class "david_perez::pages::calendars::services::calendar_service.dart::CalendarService" {
  +FirebaseFirestore firestore
  +User? currentUser
  +dynamic eliminarCitasAntiguas()
  +dynamic getUserDataFuture()
  +dynamic getClienteUid()
  +dynamic getWorkerTurn()
  +dynamic getWorkerUid()
}

"david_perez::pages::calendars::services::calendar_service.dart::CalendarService" o-- "cloud_firestore::cloud_firestore.dart::FirebaseFirestore"
"david_perez::pages::calendars::services::calendar_service.dart::CalendarService" o-- "firebase_auth::firebase_auth.dart::User"

class "david_perez::pages::facilities::add_facilities.dart::FacilitieForm" {
  +_FacilitieFormState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::pages::facilities::add_facilities.dart::FacilitieForm"

class "david_perez::pages::facilities::add_facilities.dart::_FacilitieFormState" {
  -GlobalKey<FormState> _formKey
  -TextEditingController _titleController
  -TextEditingController _descriptionController
  -bool _isSubmitting
  -void _submitForm()
  +Widget build()
}

"david_perez::pages::facilities::add_facilities.dart::_FacilitieFormState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"david_perez::pages::facilities::add_facilities.dart::_FacilitieFormState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State" <|-- "david_perez::pages::facilities::add_facilities.dart::_FacilitieFormState"

class "david_perez::pages::facilities::facilities_page.dart::Facility" {
  +String key
  +String titulo
  +String descripcion
}

class "david_perez::pages::facilities::facilities_page.dart::FacilitiesList" {
  +FacilitiesListState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::pages::facilities::facilities_page.dart::FacilitiesList"

class "david_perez::pages::facilities::facilities_page.dart::FacilitiesListState" {
  -List<Facility> _facilities
  +User? currentUser
  +UserIsAdmin userIsAdmin
  +bool isAdmin
  +void initState()
  +dynamic obtenerServicios()
  +Widget build()
}

"david_perez::pages::facilities::facilities_page.dart::FacilitiesListState" o-- "firebase_auth::firebase_auth.dart::User"
"david_perez::pages::facilities::facilities_page.dart::FacilitiesListState" o-- "david_perez::read_data::get_user_is_admin.dart::UserIsAdmin"
"flutter::src::widgets::framework.dart::State" <|-- "david_perez::pages::facilities::facilities_page.dart::FacilitiesListState"

class "david_perez::pages::forgot_pw_page.dart::ForgotPasswordPage" {
  +State<ForgotPasswordPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::pages::forgot_pw_page.dart::ForgotPasswordPage"

class "david_perez::pages::forgot_pw_page.dart::_ForgotPasswordPageState" {
  -TextEditingController _emailController
  +void dispose()
  +dynamic passwordReset()
  +Widget build()
}

"david_perez::pages::forgot_pw_page.dart::_ForgotPasswordPageState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State" <|-- "david_perez::pages::forgot_pw_page.dart::_ForgotPasswordPageState"

class "david_perez::pages::home_page.dart::HomePage" {
  +State<HomePage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::pages::home_page.dart::HomePage"

class "david_perez::pages::home_page.dart::_HomePageState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "david_perez::pages::home_page.dart::_HomePageState"

class "david_perez::pages::jobs_page.dart::ListJobs" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "david_perez::pages::jobs_page.dart::ListJobs"

class "david_perez::pages::login_page.dart::LoginPage" {
  +void Function() showRegisterPage
  +State<LoginPage> createState()
}

"david_perez::pages::login_page.dart::LoginPage" o-- "dart::ui::void Function()"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::pages::login_page.dart::LoginPage"

class "david_perez::pages::login_page.dart::_LoginPageState" {
  +TextEditingController emailController
  +TextEditingController passwordController
  +bool validateFields()
  +Widget build()
}

"david_perez::pages::login_page.dart::_LoginPageState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State" <|-- "david_perez::pages::login_page.dart::_LoginPageState"

class "david_perez::pages::maintenances::add_maintenance.dart::MaintenanceForm" {
  +_MaintenanceFormState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::pages::maintenances::add_maintenance.dart::MaintenanceForm"

class "david_perez::pages::maintenances::add_maintenance.dart::_MaintenanceFormState" {
  -GlobalKey<FormState> _formKey
  -TextEditingController _titleController
  -TextEditingController _descriptionController
  -bool _isSubmitting
  -void _submitForm()
  +Widget build()
}

"david_perez::pages::maintenances::add_maintenance.dart::_MaintenanceFormState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"david_perez::pages::maintenances::add_maintenance.dart::_MaintenanceFormState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State" <|-- "david_perez::pages::maintenances::add_maintenance.dart::_MaintenanceFormState"

class "david_perez::pages::maintenances::maintenance_page.dart::Maintenance" {
  +String key
  +String title
  +String description
}

class "david_perez::pages::maintenances::maintenance_page.dart::MaintenanceList" {
  +MaintenanceListState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::pages::maintenances::maintenance_page.dart::MaintenanceList"

class "david_perez::pages::maintenances::maintenance_page.dart::MaintenanceListState" {
  -List<Maintenance> _maintenances
  +User? currentUser
  +UserIsAdmin userIsAdmin
  +bool isAdmin
  +void initState()
  +dynamic obtenerMaintenances()
  +Widget build()
}

"david_perez::pages::maintenances::maintenance_page.dart::MaintenanceListState" o-- "firebase_auth::firebase_auth.dart::User"
"david_perez::pages::maintenances::maintenance_page.dart::MaintenanceListState" o-- "david_perez::read_data::get_user_is_admin.dart::UserIsAdmin"
"flutter::src::widgets::framework.dart::State" <|-- "david_perez::pages::maintenances::maintenance_page.dart::MaintenanceListState"

class "david_perez::pages::manage_page.dart::ManagePage" {
  +User? currentUser
  +State<ManagePage> createState()
}

"david_perez::pages::manage_page.dart::ManagePage" o-- "firebase_auth::firebase_auth.dart::User"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::pages::manage_page.dart::ManagePage"

class "david_perez::pages::manage_page.dart::_ManagePageState" {
  +Widget build()
  -Widget _buildCard()
}

"flutter::src::widgets::framework.dart::State" <|-- "david_perez::pages::manage_page.dart::_ManagePageState"

class "david_perez::pages::products_page.dart::ListProducts" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "david_perez::pages::products_page.dart::ListProducts"

class "david_perez::pages::profile::manage::delete_user.dart::UserDeleteService" {
  -FirebaseAuth _auth
  +dynamic deleteUserByEmail()
}

"david_perez::pages::profile::manage::delete_user.dart::UserDeleteService" o-- "firebase_auth::firebase_auth.dart::FirebaseAuth"

class "david_perez::pages::profile::manage::edit_user.dart::UserEditor" {
  {static} +void editUserName()
  {static} +void editUserLastName()
  {static} +void editUserPhone()
  {static} +void editUserTurn()
}

class "david_perez::pages::profile::profile_page.dart::PerfilPage" {
  +dynamic userEmail
  +State<PerfilPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::pages::profile::profile_page.dart::PerfilPage"

class "david_perez::pages::profile::profile_page.dart::_PerfilPageState" {
  +UserDeleteService userDeleteService
  +User? currentUser
  +List<String> docIDs
  +String documentID
  +UserDocumentID userDocumentID
  +void initState()
  +Stream<QuerySnapshot<Object?>> getDocsStream()
  +void confirmDeletion()
  +Widget build()
}

"david_perez::pages::profile::profile_page.dart::_PerfilPageState" o-- "david_perez::pages::profile::manage::delete_user.dart::UserDeleteService"
"david_perez::pages::profile::profile_page.dart::_PerfilPageState" o-- "firebase_auth::firebase_auth.dart::User"
"david_perez::pages::profile::profile_page.dart::_PerfilPageState" o-- "david_perez::read_data::get_user_document_id.dart::UserDocumentID"
"flutter::src::widgets::framework.dart::State" <|-- "david_perez::pages::profile::profile_page.dart::_PerfilPageState"

class "david_perez::pages::register_page.dart::RegisterPage" {
  +void Function() showLoginPage
  +State<RegisterPage> createState()
}

"david_perez::pages::register_page.dart::RegisterPage" o-- "dart::ui::void Function()"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::pages::register_page.dart::RegisterPage"

class "david_perez::pages::register_page.dart::_RegisterPageState" {
  +TextEditingController emailController
  +TextEditingController passwordController
  +TextEditingController confirmPasswordController
  +TextEditingController nameController
  +TextEditingController lastNameController
  +TextEditingController phoneController
  +bool isWorker
  +TextEditingController code
  +Widget build()
}

"david_perez::pages::register_page.dart::_RegisterPageState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State" <|-- "david_perez::pages::register_page.dart::_RegisterPageState"

class "david_perez::pages::services::add_service.dart::ServiceForm" {
  +_ServiceFormState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::pages::services::add_service.dart::ServiceForm"

class "david_perez::pages::services::add_service.dart::_ServiceFormState" {
  -GlobalKey<FormState> _formKey
  -TextEditingController _titleController
  -TextEditingController _descriptionController
  -bool _isSubmitting
  -void _submitForm()
  +Widget build()
}

"david_perez::pages::services::add_service.dart::_ServiceFormState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"david_perez::pages::services::add_service.dart::_ServiceFormState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State" <|-- "david_perez::pages::services::add_service.dart::_ServiceFormState"

class "david_perez::pages::services::services_page.dart::Servicio" {
  +String key
  +String title
  +String description
}

class "david_perez::pages::services::services_page.dart::ServicesList" {
  +ServicesListState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::pages::services::services_page.dart::ServicesList"

class "david_perez::pages::services::services_page.dart::ServicesListState" {
  -List<Servicio> _servicios
  +User? currentUser
  +UserIsAdmin userIsAdmin
  +bool isAdmin
  +void initState()
  +dynamic obtenerServicios()
  +Widget build()
}

"david_perez::pages::services::services_page.dart::ServicesListState" o-- "firebase_auth::firebase_auth.dart::User"
"david_perez::pages::services::services_page.dart::ServicesListState" o-- "david_perez::read_data::get_user_is_admin.dart::UserIsAdmin"
"flutter::src::widgets::framework.dart::State" <|-- "david_perez::pages::services::services_page.dart::ServicesListState"

class "david_perez::pages::workers_page.dart::ListWorkers" {
  +dynamic user
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "david_perez::pages::workers_page.dart::ListWorkers"

class "david_perez::read_data::get_user_apellidos.dart::GetUserLastName" {
  +String documentId
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "david_perez::read_data::get_user_apellidos.dart::GetUserLastName"

class "david_perez::read_data::get_user_document_id.dart::UserDocumentID" {
  +String? userEmail
  +String documentID
  +dynamic getUserDocumentID()
}

class "david_perez::read_data::get_user_email.dart::GetUserEmail" {
  +String documentId
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "david_perez::read_data::get_user_email.dart::GetUserEmail"

class "david_perez::read_data::get_user_horario.dart::GetUserTurno" {
  +String workerDocumentId
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "david_perez::read_data::get_user_horario.dart::GetUserTurno"

class "david_perez::read_data::get_user_is_admin.dart::UserIsAdmin" {
  +User? user
  +bool isAdmin
  +dynamic getUser()
}

"david_perez::read_data::get_user_is_admin.dart::UserIsAdmin" o-- "firebase_auth::firebase_auth.dart::User"

class "david_perez::read_data::get_user_is_worker.dart::UserIsWorker" {
  +User? user
  +bool isWorker
  +dynamic getUser()
}

"david_perez::read_data::get_user_is_worker.dart::UserIsWorker" o-- "firebase_auth::firebase_auth.dart::User"

class "david_perez::read_data::get_user_name.dart::GetUserName" {
  +String documentId
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "david_perez::read_data::get_user_name.dart::GetUserName"

class "david_perez::read_data::get_user_telefono.dart::GetUserTelefono" {
  +String documentId
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "david_perez::read_data::get_user_telefono.dart::GetUserTelefono"

class "david_perez::services::user_auth.dart::UserAuth" {
  +TextEditingController emailController
  +TextEditingController passwordController
  +BuildContext context
  +FirebaseAuth auth
  -GoogleSignIn _googleSignIn
  +dynamic signUserIn()
  +dynamic wrongEmailMessage()
  +dynamic wrongPasswordMessage()
  +dynamic signOutGoogle()
}

"david_perez::services::user_auth.dart::UserAuth" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"david_perez::services::user_auth.dart::UserAuth" o-- "flutter::src::widgets::framework.dart::BuildContext"
"david_perez::services::user_auth.dart::UserAuth" o-- "firebase_auth::firebase_auth.dart::FirebaseAuth"
"david_perez::services::user_auth.dart::UserAuth" o-- "google_sign_in::google_sign_in.dart::GoogleSignIn"

class "david_perez::services::user_register.dart::UserRegister" {
  +TextEditingController emailController
  +TextEditingController passwordController
  +TextEditingController confirmPasswordController
  +TextEditingController nameController
  +TextEditingController lastNameController
  +TextEditingController phoneController
  +TextEditingController code
  +BuildContext context
  +bool isWorker
  +bool isBoss
  +bool isMeasurer
  +dynamic isCodeValid()
  +dynamic signUp()
  +bool isEmailValid()
  +bool isPhoneNumberValid()
  +bool isPasswordStrongEnough()
  +dynamic checkEmailInUse()
  +void wrongMessage()
  +dynamic addUserDetails()
  +bool passwordConfirmed()
}

"david_perez::services::user_register.dart::UserRegister" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"david_perez::services::user_register.dart::UserRegister" o-- "flutter::src::widgets::framework.dart::BuildContext"

class "david_perez::widgets::bookings::delete_booking.dart::DeleteBookingDialog" {
  +DocumentSnapshot<Object?> booking
  +DeleteBookingDialogState createState()
}

"david_perez::widgets::bookings::delete_booking.dart::DeleteBookingDialog" o-- "cloud_firestore::cloud_firestore.dart::DocumentSnapshot<Object>"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::widgets::bookings::delete_booking.dart::DeleteBookingDialog"

class "david_perez::widgets::bookings::delete_booking.dart::DeleteBookingDialogState" {
  +void deleteBooking()
  +void deleteTask()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "david_perez::widgets::bookings::delete_booking.dart::DeleteBookingDialogState"

class "david_perez::widgets::bookings::show_booking.dart::ShowBookingDialog" {
  +DocumentSnapshot<Object?> booking
  +ShowBookingDialogState createState()
}

"david_perez::widgets::bookings::show_booking.dart::ShowBookingDialog" o-- "cloud_firestore::cloud_firestore.dart::DocumentSnapshot<Object>"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::widgets::bookings::show_booking.dart::ShowBookingDialog"

class "david_perez::widgets::bookings::show_booking.dart::ShowBookingDialogState" {
  +TextEditingController dateController
  +TextEditingController productController
  +bool isPaid
  +void initState()
  +dynamic getProductData()
  +dynamic getProductById()
  -void _showFlipCardDialog()
  +Widget build()
}

"david_perez::widgets::bookings::show_booking.dart::ShowBookingDialogState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State" <|-- "david_perez::widgets::bookings::show_booking.dart::ShowBookingDialogState"

class "david_perez::widgets::custom_appbar.dart::CustomAppBar" {
  +bool showBackArrow
  +Size preferredSize
  +Widget build()
}

"david_perez::widgets::custom_appbar.dart::CustomAppBar" o-- "dart::ui::Size"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "david_perez::widgets::custom_appbar.dart::CustomAppBar"
"flutter::src::widgets::preferred_size.dart::PreferredSizeWidget" <|-- "david_perez::widgets::custom_appbar.dart::CustomAppBar"

class "david_perez::widgets::custom_drawer.dart::CustomDrawer" {
  +User? currentUser
  +State<CustomDrawer> createState()
}

"david_perez::widgets::custom_drawer.dart::CustomDrawer" o-- "firebase_auth::firebase_auth.dart::User"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::widgets::custom_drawer.dart::CustomDrawer"

class "david_perez::widgets::custom_drawer.dart::_CustomDrawerState" {
  +bool isWorker
  +bool isAdmin
  +String documentID
  +UserIsAdmin userIsAdmin
  +UserIsWorker userIsWorker
  +UserDocumentID userDocumentID
  +void initState()
  +Widget build()
}

"david_perez::widgets::custom_drawer.dart::_CustomDrawerState" o-- "david_perez::read_data::get_user_is_admin.dart::UserIsAdmin"
"david_perez::widgets::custom_drawer.dart::_CustomDrawerState" o-- "david_perez::read_data::get_user_is_worker.dart::UserIsWorker"
"david_perez::widgets::custom_drawer.dart::_CustomDrawerState" o-- "david_perez::read_data::get_user_document_id.dart::UserDocumentID"
"flutter::src::widgets::framework.dart::State" <|-- "david_perez::widgets::custom_drawer.dart::_CustomDrawerState"

class "david_perez::widgets::icons.dart::CircleIconsWidget" {
  +String whatsappNumber
  +String phoneNumber
  +String instagramProfile
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "david_perez::widgets::icons.dart::CircleIconsWidget"

class "david_perez::widgets::icons_home.dart::IconsHome" {
  +String iconURL
  +String text
  +Widget page
  +_IconsHomeState createState()
}

"david_perez::widgets::icons_home.dart::IconsHome" o-- "flutter::src::widgets::framework.dart::Widget"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::widgets::icons_home.dart::IconsHome"

class "david_perez::widgets::icons_home.dart::_IconsHomeState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "david_perez::widgets::icons_home.dart::_IconsHomeState"

class "david_perez::widgets::jobs::add_job.dart::JobForm" {
  +_JobFormState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::widgets::jobs::add_job.dart::JobForm"

class "david_perez::widgets::jobs::add_job.dart::_JobFormState" {
  -GlobalKey<FormState> _formKey
  -TextEditingController _titleController
  -TextEditingController _descriptionController
  -File? _image
  -bool _isSubmitting
  -String? _imageError
  -dynamic _pickImage()
  -dynamic _uploadImageToStorage()
  -void _submitForm()
  +Widget build()
}

"david_perez::widgets::jobs::add_job.dart::_JobFormState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"david_perez::widgets::jobs::add_job.dart::_JobFormState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"david_perez::widgets::jobs::add_job.dart::_JobFormState" o-- "dart::io::File"
"flutter::src::widgets::framework.dart::State" <|-- "david_perez::widgets::jobs::add_job.dart::_JobFormState"

class "david_perez::widgets::jobs::edit_job.dart::EditJob" {
  +dynamic job
  +State<EditJob> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::widgets::jobs::edit_job.dart::EditJob"

class "david_perez::widgets::jobs::edit_job.dart::_EditJobState" {
  -String _title
  -String _description
  -File? _image
  -String? _imageUrlFromDatabase
  +String jobID
  -GlobalKey<FormState> _formKey
  +CollectionReference<Object?> jobsCollection
  -dynamic _pickImage()
  -dynamic _uploadImageToStorage()
  -dynamic _deletePreviousImage()
  -void _showLoadingDialog()
  -Widget _buildImage()
  +Widget build()
}

"david_perez::widgets::jobs::edit_job.dart::_EditJobState" o-- "dart::io::File"
"david_perez::widgets::jobs::edit_job.dart::_EditJobState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"david_perez::widgets::jobs::edit_job.dart::_EditJobState" o-- "cloud_firestore::cloud_firestore.dart::CollectionReference<Object>"
"flutter::src::widgets::framework.dart::State" <|-- "david_perez::widgets::jobs::edit_job.dart::_EditJobState"

class "david_perez::widgets::jobs::jobs_row.dart::JobsCardsRow" {
  +User? currentUser
  +State<JobsCardsRow> createState()
}

"david_perez::widgets::jobs::jobs_row.dart::JobsCardsRow" o-- "firebase_auth::firebase_auth.dart::User"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::widgets::jobs::jobs_row.dart::JobsCardsRow"

class "david_perez::widgets::jobs::jobs_row.dart::_JobsCardsRowState" {
  +FirebaseFirestore database
  +Stream<QuerySnapshot<Object?>> fetchJobsStream()
  +Widget build()
}

"david_perez::widgets::jobs::jobs_row.dart::_JobsCardsRowState" o-- "cloud_firestore::cloud_firestore.dart::FirebaseFirestore"
"flutter::src::widgets::framework.dart::State" <|-- "david_perez::widgets::jobs::jobs_row.dart::_JobsCardsRowState"

class "david_perez::widgets::jobs::job_card_widget.dart::JobCardWidget" {
  +dynamic job
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "david_perez::widgets::jobs::job_card_widget.dart::JobCardWidget"

class "david_perez::widgets::lists::bookings_list.dart::BookingsListView" {
  +User? currentUser
  +String? clienteEmail
  +Widget build()
}

"david_perez::widgets::lists::bookings_list.dart::BookingsListView" o-- "firebase_auth::firebase_auth.dart::User"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "david_perez::widgets::lists::bookings_list.dart::BookingsListView"

class "david_perez::widgets::lists::quotes_list_view.dart::CitasListView" {
  +String? clienteUid
  +DateTime? selectedDay
  +User? currentUser
  +String? clienteEmail
  +Widget build()
}

"david_perez::widgets::lists::quotes_list_view.dart::CitasListView" o-- "firebase_auth::firebase_auth.dart::User"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "david_perez::widgets::lists::quotes_list_view.dart::CitasListView"

class "david_perez::widgets::lists::task_list_view.dart::TaskListView" {
  +String? workerUid
  +DateTime? selectedDay
  +bool? isAssigned
  +String? userEmail
  +String workerEmail
  +bool? edit
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "david_perez::widgets::lists::task_list_view.dart::TaskListView"

class "david_perez::widgets::my_button.dart::MyButton" {
  +dynamic Function()? onTap
  +String text
  +Widget build()
}

"david_perez::widgets::my_button.dart::MyButton" o-- "null::dynamic Function()"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "david_perez::widgets::my_button.dart::MyButton"

class "david_perez::widgets::my_textfield.dart::MyTextField" {
  +TextEditingController controller
  +String hintText
  +bool obscureText
  +State<MyTextField> createState()
}

"david_perez::widgets::my_textfield.dart::MyTextField" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::widgets::my_textfield.dart::MyTextField"

class "david_perez::widgets::my_textfield.dart::_MyTextFieldState" {
  +bool obscureText
  +void initState()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "david_perez::widgets::my_textfield.dart::_MyTextFieldState"

class "david_perez::widgets::products::add_product.dart::ProductForm" {
  +_ProductFormState createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::widgets::products::add_product.dart::ProductForm"

class "david_perez::widgets::products::add_product.dart::_ProductFormState" {
  -GlobalKey<FormState> _formKey
  -TextEditingController _titleController
  -TextEditingController _descriptionController
  -TextEditingController _priceController
  -TextEditingController _stockController
  -File? _image
  -bool _isSubmitting
  -String? _imageError
  -dynamic _pickImage()
  -dynamic _uploadImageToStorage()
  -void _submitForm()
  +Widget build()
}

"david_perez::widgets::products::add_product.dart::_ProductFormState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"david_perez::widgets::products::add_product.dart::_ProductFormState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"david_perez::widgets::products::add_product.dart::_ProductFormState" o-- "dart::io::File"
"flutter::src::widgets::framework.dart::State" <|-- "david_perez::widgets::products::add_product.dart::_ProductFormState"

class "david_perez::widgets::products::edit_product.dart::EditProduct" {
  +dynamic product
  +State<EditProduct> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::widgets::products::edit_product.dart::EditProduct"

class "david_perez::widgets::products::edit_product.dart::_EditProductState" {
  -String _title
  -String _description
  -String _price
  -String _cantidad
  -File? _image
  -String? _imageUrlFromDatabase
  +String productID
  -GlobalKey<FormState> _formKey
  +CollectionReference<Object?> productsCollection
  -dynamic _pickImage()
  -dynamic _uploadImageToStorage()
  -dynamic _deletePreviousImage()
  -void _showLoadingDialog()
  -Widget _buildImage()
  +Widget build()
}

"david_perez::widgets::products::edit_product.dart::_EditProductState" o-- "dart::io::File"
"david_perez::widgets::products::edit_product.dart::_EditProductState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"david_perez::widgets::products::edit_product.dart::_EditProductState" o-- "cloud_firestore::cloud_firestore.dart::CollectionReference<Object>"
"flutter::src::widgets::framework.dart::State" <|-- "david_perez::widgets::products::edit_product.dart::_EditProductState"

class "david_perez::widgets::products::products_colum.dart::ProductsCardColumn" {
  +User? currentUser
  +State<ProductsCardColumn> createState()
}

"david_perez::widgets::products::products_colum.dart::ProductsCardColumn" o-- "firebase_auth::firebase_auth.dart::User"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::widgets::products::products_colum.dart::ProductsCardColumn"

class "david_perez::widgets::products::products_colum.dart::_ProductsCardColumnState" {
  +FirebaseFirestore database
  +Stream<QuerySnapshot<Object?>> fetchProductsStream()
  +Widget build()
}

"david_perez::widgets::products::products_colum.dart::_ProductsCardColumnState" o-- "cloud_firestore::cloud_firestore.dart::FirebaseFirestore"
"flutter::src::widgets::framework.dart::State" <|-- "david_perez::widgets::products::products_colum.dart::_ProductsCardColumnState"

class "david_perez::widgets::products::product_card_widget.dart::ProductCardWidget" {
  +String productID
  +dynamic product
  +State<ProductCardWidget> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::widgets::products::product_card_widget.dart::ProductCardWidget"

class "david_perez::widgets::products::product_card_widget.dart::_ProductCardWidgetState" {
  +User? currentUser
  -GlobalKey<ScaffoldState> _scaffoldKey
  +bool isLoading
  -GlobalKey<FormState> _formKey
  +Stream<QuerySnapshot<Object?>> getDocsStream()
  +dynamic sendEmail()
  -dynamic _showConfirmationDialog()
  +Widget build()
}

"david_perez::widgets::products::product_card_widget.dart::_ProductCardWidgetState" o-- "firebase_auth::firebase_auth.dart::User"
"david_perez::widgets::products::product_card_widget.dart::_ProductCardWidgetState" o-- "flutter::src::widgets::framework.dart::GlobalKey<ScaffoldState>"
"david_perez::widgets::products::product_card_widget.dart::_ProductCardWidgetState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"flutter::src::widgets::framework.dart::State" <|-- "david_perez::widgets::products::product_card_widget.dart::_ProductCardWidgetState"

class "david_perez::widgets::quotes::delete_quote.dart::DeleteQuoteDialog" {
  +DocumentSnapshot<Object?> quote
  +DeleteQuoteDialogState createState()
}

"david_perez::widgets::quotes::delete_quote.dart::DeleteQuoteDialog" o-- "cloud_firestore::cloud_firestore.dart::DocumentSnapshot<Object>"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::widgets::quotes::delete_quote.dart::DeleteQuoteDialog"

class "david_perez::widgets::quotes::delete_quote.dart::DeleteQuoteDialogState" {
  +void deleteQuote()
  +void deleteTask()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "david_perez::widgets::quotes::delete_quote.dart::DeleteQuoteDialogState"

class "david_perez::widgets::quotes::show_quote.dart::ShowQuoteDialog" {
  +DocumentSnapshot<Object?> quote
  +ShowQuoteDialogState createState()
}

"david_perez::widgets::quotes::show_quote.dart::ShowQuoteDialog" o-- "cloud_firestore::cloud_firestore.dart::DocumentSnapshot<Object>"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::widgets::quotes::show_quote.dart::ShowQuoteDialog"

class "david_perez::widgets::quotes::show_quote.dart::ShowQuoteDialogState" {
  +TextEditingController addressController
  +TextEditingController dateController
  +bool isImportant
  +bool isDone
  +void initState()
  +Widget build()
}

"david_perez::widgets::quotes::show_quote.dart::ShowQuoteDialogState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State" <|-- "david_perez::widgets::quotes::show_quote.dart::ShowQuoteDialogState"

class "david_perez::widgets::square_tile.dart::SquareTile" {
  +String imagePath
  +dynamic Function()? onTap
  +Widget build()
}

"david_perez::widgets::square_tile.dart::SquareTile" o-- "null::dynamic Function()"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "david_perez::widgets::square_tile.dart::SquareTile"

class "david_perez::widgets::task::create_task.dart::CreateTask" {
  +TextEditingController tituloController
  +TextEditingController descripcionController
  +DateTime? fecha
  +bool importante
  +String worker
  +String workerEmail
  +String autorEmail
  +dynamic addTaskToDatabase()
  +bool isTitleValid()
  +bool isDescriptionValid()
}

"david_perez::widgets::task::create_task.dart::CreateTask" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"

class "david_perez::widgets::task::create_task_page.dart::CreateTaskPage" {
  +String workerUid
  +dynamic user
  +String workerEmail
  +DateTime? selectedDay
  +State<CreateTaskPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::widgets::task::create_task_page.dart::CreateTaskPage"

class "david_perez::widgets::task::create_task_page.dart::_CreateTaskPageState" {
  +TextEditingController tituloController
  +TextEditingController descripcionController
  +TimeOfDay selectedTime
  -bool _esImportante
  +void initState()
  +dynamic selectTime()
  +Widget build()
}

"david_perez::widgets::task::create_task_page.dart::_CreateTaskPageState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"david_perez::widgets::task::create_task_page.dart::_CreateTaskPageState" o-- "flutter::src::material::time.dart::TimeOfDay"
"flutter::src::widgets::framework.dart::State" <|-- "david_perez::widgets::task::create_task_page.dart::_CreateTaskPageState"

class "david_perez::widgets::task::delete_task.dart::DeleteTaskDialog" {
  +DocumentSnapshot<Object?> task
  +DeleteTaskDialogState createState()
}

"david_perez::widgets::task::delete_task.dart::DeleteTaskDialog" o-- "cloud_firestore::cloud_firestore.dart::DocumentSnapshot<Object>"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::widgets::task::delete_task.dart::DeleteTaskDialog"

class "david_perez::widgets::task::delete_task.dart::DeleteTaskDialogState" {
  +void deleteQuote()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "david_perez::widgets::task::delete_task.dart::DeleteTaskDialogState"

class "david_perez::widgets::task::edit_task.dart::EditTaskDialog" {
  +DocumentSnapshot<Object?> task
  +EditTaskDialogState createState()
}

"david_perez::widgets::task::edit_task.dart::EditTaskDialog" o-- "cloud_firestore::cloud_firestore.dart::DocumentSnapshot<Object>"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::widgets::task::edit_task.dart::EditTaskDialog"

"david_perez::widgets::task::show_task.dart::ShowTaskDialog" o-- "cloud_firestore::cloud_firestore.dart::DocumentSnapshot<Object>"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "david_perez::widgets::task::show_task.dart::ShowTaskDialog"

class "david_perez::widgets::task::show_task.dart::ShowTaskDialogState" {
  +TextEditingController titleController
  +TextEditingController descriptionController
  +TextEditingController addressController
  +TextEditingController dateController
  +bool isImportant
  +bool isDone
  +void initState()
  +Widget build()
}

"david_perez::widgets::task::show_task.dart::ShowTaskDialogState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State" <|-- "david_perez::widgets::task::show_task.dart::ShowTaskDialogState"


@enduml