// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlccJJBtXWOwVG2GXqMtnjoHYUWKto3bw',
    appId: '1:1050381474150:web:a3fe5a59e516de2db550a7',
    messagingSenderId: '1050381474150',
    projectId: 'carpinteria-dp',
    authDomain: 'carpinteria-dp.firebaseapp.com',
    storageBucket: 'carpinteria-dp.appspot.com',
    measurementId: 'G-E40XT3XQ1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5oKcAxpxi9zBWsH9H4jKQRFYHQ3rqEJE',
    appId: '1:1050381474150:android:0543b6919c180114b550a7',
    messagingSenderId: '1050381474150',
    projectId: 'carpinteria-dp',
    storageBucket: 'carpinteria-dp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW-91ZqibnO_6XW1RGbvvc6K26TidHhUg',
    appId: '1:1050381474150:ios:fe29a311775d3b1cb550a7',
    messagingSenderId: '1050381474150',
    projectId: 'carpinteria-dp',
    storageBucket: 'carpinteria-dp.appspot.com',
    iosClientId: '1050381474150-gnj2m0hiishfj759al1c67bghr2gf6un.apps.googleusercontent.com',
    iosBundleId: 'com.example.carpinteria-dp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW-91ZqibnO_6XW1RGbvvc6K26TidHhUg',
    appId: '1:1050381474150:ios:fe29a311775d3b1cb550a7',
    messagingSenderId: '1050381474150',
    projectId: 'carpinteria-dp',
    storageBucket: 'carpinteria-dp.appspot.com',
    iosClientId: '1050381474150-gnj2m0hiishfj759al1c67bghr2gf6un.apps.googleusercontent.com',
    iosBundleId: 'com.example.carpinteria-dp',
  );
}
